
name = "slm-libzip"
version = "0.1.4"

[dependencies.libzip]
pkg="libzip"
version="1.10.1"
type="conan"
options.shared = "True"
options.tools = "True"
options.with_bzip2 = "True"
options.with_lzma = "True"
options.with_zstd = "True"
options.linux.crypto = "openssl"
options.macos.crypto = "openssl"
options.windows.crypto = "win32"

#options.linux.fPIC = "True"
#options.macos.fPIC = "True"

[dependencies.zlib]
pkg="zlib"
version="1.3.1"
type="conan"
options.shared = "True"

[dependencies.bzip2]
pkg="bzip2"
version="1.0.8"
type="conan"
options.shared = "True"
options.build_executable = "False"

[dependencies.zstd]
pkg="zstd"
version="1.5.5"
type="conan"
options.shared = "True"
options.build_programs = "True"
options.threading = "True"

[dependencies.openssl]
pkg="openssl"
version="3.2.2"
type="conan"
options.shared = "True"
options.386 = "False"
options.enable_trace = "False"
options.enable_weak_ssl_ciphers = "False"
options.no_apps = "False"
options.no_aria = "False"
options.no_asm = "False"
options.no_async = "False"
options.no_autoload_config = "False"
options.no_bf = "False"
options.no_blake2 = "False"
options.no_camellia = "False"
options.no_cast = "False"
options.no_chacha = "False"
options.no_cms = "False"
options.no_comp = "False"
options.no_ct = "False"
options.no_deprecated = "False"
options.no_des = "False"
options.no_dgram = "False"
options.no_dh = "False"
options.no_dsa = "False"
options.no_dso = "False"
options.no_ec = "False"
options.no_ecdh = "False"
options.no_ecdsa = "False"
options.no_engine = "False"
options.no_filenames = "False"
options.no_fips = "False"
options.no_gost = "False"
options.no_idea = "False"
options.no_legacy = "False"
options.no_md2 = "True"
options.no_md4 = "False"
options.no_mdc2 = "False"
options.no_module = "False"
options.no_ocsp = "False"
options.no_pinshared = "False"
options.no_rc2 = "False"
options.no_rc4 = "False"
options.no_rc5 = "False"
options.no_rfc3779 = "False"
options.no_rmd160 = "False"
options.no_seed = "False"
options.no_sm2 = "False"
options.no_sm3 = "False"
options.no_sm4 = "False"
options.no_sock = "False"
options.no_srp = "False"
options.no_srtp = "False"
options.no_sse2 = "False"
options.no_ssl = "False"
options.no_ssl3 = "False"
options.no_stdio = "False"
options.no_threads = "False"
options.no_tls1 = "False"
options.no_ts = "False"
options.no_whirlpool = "False"
options.no_zlib = "False"
options.windows.capieng_dialog = "False"
options.windows.enable_capieng = "False"

[dependencies.xz_utils]
pkg="xz_utils"
version="5.4.5"
type="conan"
options.shared = "True"
